### ISSUE TITLE
cant switch colors

### ISSUE THREAD

**Issue by pravendrakushwaha** [luximus-hunter/accented#1]
i wont able to switch colors
![Screenshot (821)](https://user-images.githubusercontent.com/17412877/172038507-ecd41152-a0f3-4d19-a487-39b6b059f5c8.png)

**Comment by Mabeli-clown** [comment]
right-up corner,,,

**Comment by luximus-hunter** [comment]
This seems to be an issue with your spicetify marketplace. I can't recreate this 😅
